#\u542F\u52A8\u7AEF\u53E3
server.port=15008
#\u5E94\u7528\u540D\u79F0
spring.application.name=imooc-bilibili-zuul
#redis
spring.redis.host=192.168.88.130
spring.redis.port=6379
spring.redis.password=redis1031
#\u8DEF\u7531\u914D\u7F6E
zuul.routes.imooc-bilibili-api.path=/imooc-bilibili-api/**
zuul.routes.imooc-bilibili-api.service-id=imooc-bilibili-api
#eureka
eureka.instance.instanceId=${spring.cloud.client.ip-address}:${server.port}
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:15006/eureka/